//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleMap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marker
    {
        public Marker()
        {
            this.MarkerComments = new HashSet<MarkerComment>();
            this.MarkerLikes = new HashSet<MarkerLike>();
            this.Pictures = new HashSet<Picture>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid SubCategoryId { get; set; }
        public string Name { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Website { get; set; }
        public string Status { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> TotalLikes { get; set; }
        public Nullable<int> TotalComment { get; set; }
    
        public virtual ICollection<MarkerComment> MarkerComments { get; set; }
        public virtual ICollection<MarkerLike> MarkerLikes { get; set; }
        public virtual SubCategory SubCategory { get; set; }
        public virtual ICollection<Picture> Pictures { get; set; }
    }
}
