//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleMap.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GoogleMapEntities : DbContext
    {
        public GoogleMapEntities()
            : base("name=GoogleMapEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Category> Categories { get; set; }
        public DbSet<Layer> Layers { get; set; }
        public DbSet<MarkerComment> MarkerComments { get; set; }
        public DbSet<MarkerLike> MarkerLikes { get; set; }
        public DbSet<Marker> Markers { get; set; }
        public DbSet<Picture> Pictures { get; set; }
        public DbSet<SubCategory> SubCategories { get; set; }
    }
}
